# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Declare the Python requirements required
# to build documentation
python:
   install:
   - requirements: docs/requirements.txt